name: variable workflow
on: push
env:
    SUBSCRIBE: subscribe
    CHANNEL: devops
    LIKE: please like share
jobs:
    run-environment-variable:
        runs-on: ubuntu-latest
        
        steps:
            -   name: sample for an youtube channel
                run: echo "$LIKE and $SUBSCRIBE  $CHANNEL"
                
                

        
                