name: variable workflow
on: workflow_dispatch
env:
    SUBSCRIBE: subscribe
jobs:
    run-environment-variable:
        runs-on: ubuntu-latest
        env: 
            LIKE: please like share
        steps:
            -   name: sample for an youtube channel
                run: echo "$LIKE and $SUBSCRIBE  $CHANNEL"
                
                env:
                    CHANNEL: devops

        
                